version: 0.2

phases:
  pre_build:
    commands:
      - n 22

  build:
    commands:
      - node -v
      - npm -v
      - npm install
      - npm run build
      - zip -r bootstrap.zip .output/server

  post_build:
    commands:
      - echo "Running post_build commands"

artifacts:
  files:
    - bootstrap.zip
  discard-paths: yes
