version: 0.2

phases:
  pre_build:
    commands:
      - touch ~/.bash_profile
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

  build:
    commands:
      - nvm install 22
      - nvm use node
      - node -v
      - npm -v
      - npm install
      - npm run build
      - zip -r bootstrap.zip .output/server

  post_build:
    commands:
      - echo "Running post_build commands"

artifacts:
  files:
    - bootstrap.zip
  discard-paths: yes
