version: 0.2

phases:
  pre_build:
    commands:
      # update nodejs to version 22
      - n 22

  build:
    commands:
      - node -v
      - npm -v
      - npm install
      - npm run build
      - cd .output/server
      - zip -r nuxt-lambda.zip .
      - cd ../..
      - mv .output/server/nuxt-lambda.zip nuxt-lambda.zip
      - rsync -Hav .output/public/ ./public/

  post_build:
    commands:
      - echo "Running post_build commands"

artifacts:
  files:
    - nuxt-lambda.zip
    - 'public/**/*'
  discard-paths: yes
