version: 0.2

env:
  parameter-store:
    ELASTICACHE_ENDPOINT: "ELASTICACHE_ENDPOINT"

phases:
  pre_build:
    commands:
      # update nodejs to version 22
      - n 22
      
  build:
    commands:
      - node -v
      - npm -v
      - npm ci
      - npm run build
      - cd .output/server
      - zip -r nuxt-lambda.zip .
      - cd ../..
      - mv .output/server/nuxt-lambda.zip nuxt-lambda.zip
      - rsync -Hav .output/public/ ./static/
      - rsync -Hav ./node_modules/govuk-frontend/dist/govuk/assets/ ./static/assets/

  post_build:
    commands:
      - echo "Running post_build commands"

artifacts:
  files:
    - nuxt-lambda.zip
    - 'static/**/*'
