version: 0.2

phases:
  build:
    commands:
      - bash ./scripts/assume_role.sh arn:aws:iam::$AWS_ACCOUNT_ID:role/ci-server ci_server
      - export AWS_PROFILE=ci_server
      - aws s3 sync --delete $CODEBUILD_SRC_DIR_build_frontend_output s3://epb-ecaas-front-end-s3-bucket/static/ --exclude "nuxt-lambda*"
      - aws lambda update-function-code --function-name front-end-lambda --zip-file fileb://$CODEBUILD_SRC_DIR_build_frontend_output/nuxt-lambda.zip
  post_build:
    commands:
      - echo "Running post_build commands"
