version: 0.2
env:
  parameter-store:
    LOGIN_USERNAME: "LOGIN_USERNAME"
    LOGIN_PASSWORD: "LOGIN_PASSWORD"

    
phases:
  build:
    commands:
      - npm ci
      - npx playwright install --with-deps
      - export BASE_URL=$ECAAS_URL
      - mkdir -p playwright/.auth
      - npm run ci-e2e-test
