version: 0.2
env:
  # variables:
    # BASE_URL: "ECAAS_URL"
  parameter-store:
    LOGIN_USERNAME: "LOGIN_USERNAME"
    LOGIN_PASSWORD: "LOGIN_PASSWORD"

    
phases:
  pre_build:
    commands:
      # update nodejs to version 22
      - node -v

  build:
    commands:
      - npm ci
      - npx playwright install --with-deps
      - npm run ci-e2e-test
