<script setup lang="ts">
export interface GovDetailsProps {
	summaryText: string;
	classes?: string;
	possiblyLlmPlaceholder?: boolean;
}

defineProps<GovDetailsProps>();
</script>

<template>
	<details :class="`govuk-details ${classes}`">
		<summary class="govuk-details__summary">
			<span class="govuk-details__summary-text">
				{{ summaryText }}
			</span>
		</summary>
		<div class="govuk-details__text">
			<slot />
			<GovWarningText v-if="possiblyLlmPlaceholder">
				<p class="govuk-body-s">NB. The above may have been generated by an LLM as placeholder text, and should not be considered accurate.</p>
			</GovWarningText>
		</div>
	</details>
</template>