<script setup lang="ts">
defineProps<{
	classes?: string;
}>();
</script>

<template>
	<GovWarningText :classes="classes">
		<p class="govuk-body-s">Some of the typical values and guidance on this page may have been generated by an LLM, and should not be considered accurate. Official and accurate guidance will be published with the final release of this tool.</p>
	</GovWarningText>
</template>